---
title: "Deployment Performance Review of the 2019 North Pacific Observer Program"
author: "Fishery Monitoring Science Committee"
always_allow_html: true
output:
  word_document:
#    reference_docx: word-styles-reference-01.docx
  pdf_document: default
---
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Is this the annual report or the tech memo?
# This will control whether certain text chunks are included and formatting of table/figure captions.
annual.report <- TRUE
tech.memo     <- TRUE
year <- 2020

# Load packages and functions 
#source("3_helper.R")
````




##The Sampling Design of the Observer Program 
Since 2013, the Observer Program has used a stratified hierarchical sampling design with randomization at all levels. Stratification is used to increase the efficiency of sampling by observers and to address logistical issues associated with deployment. By grouping similar fishing activities into strata and sampling those strata appropriately, sampling efficiency is increased and the variance of resulting estimates may also be decreased. Sampling strata are defined in the ADP and are designed such that each unit of deployment (trip) is assigned to only one stratum.

Within a stratum, observers are deployed randomly to either vessels for a predetermined period of time (termed vessel-selection), or to individual fishing trips (termed trip-selection). In both cases, this initial deployment to the fishery is the first level of the sampling hierarchy and defines the primary sampling unit (PSU; either vessel-periods or individual trips). The list of all PSUs in a stratum defines the sampling frame and should equate to the population of interest for that sampling stratum (e.g., all trips taken by trawl vessels fishing in the Alaska EEZ).  If the sampling frame does not contain all elements of the stratum, the resulting information may be biased.  The magnitude and direction of the bias will depend on how different the fishing activities in the sample frame are from actual fishing activity.

Although this report evaluates whether monitoring goals were met, we include a brief summary of the full sampling hierarchy here for context.  For each observed trip, if all hauls cannot be sampled for logistical reasons, hauls are randomly selected to be sampled. This is the next level in the hierarchy; the secondary sampling units are defined as hauls within a trip. Randomization of haul selection is designed to allow observers to record and transmit data, attend to other non-sampling responsibilities, and to allow observers time to sleep and eat. Randomization of haul selection also gives EM video reviewers the ability to optimize the amount of video that can be reviewed from each trip. Haul selection is determined using the random sampling tables and random break tables provided by NMFS. For each haul, fishing location and effort (e.g., number of hooks) are recorded, while marine mammal and seabird interactions are primarily recorded on randomly selected hauls. The ability of EM to capture marine mammal and seabird interactions is less than that of observers due to the fixed location in which EM equipment is placed.

For the randomly selected hauls, a random sample of the catch is collected (observers) or selected for video review (EM), and data from those samples are used to determine the species composition and amount of discarded catch. These samples of catch within each haul are the third level of the sampling hierarchy. While observers are trained to collect multiple large samples of catch, the number and size of samples taken from each haul will depend on the vessel configuration, fishing operations, and diversity of catch. The size of EM samples is largely determined by the number of video reviewers available relative to the amount of video to be reviewed.

At the fourth level of the sampling hierarchy, a predetermined number of individual fish of predetermined species is randomly selected from the species composition sample and measured. Lastly, at the fifth sampling level, a random selection of fish is used to collect otoliths, reproductive maturity assessments, stomach contents, genetic tissues, and other biological specimens. The number and species of fish selected for measurement and biological specimen collection is specified each year by the AFSC’s stock assessment scientists. Sampling rates for genetic tissue collection by observers (e.g., 1 of 10 Chinook salmon caught as bycatch) are set each year by the AFSC’s Auke Bay Laboratory. Sampling at the fourth and fifth levels of the sampling hierarchy does not occur with EM. 
 
ORIGINAL AR
`r if(annual.report){'More information on the sampling design used by observers and the relationship between the sample design and catch estimation can be found in Cahalan and Faunce (2020) and the 2019 Observer Sampling Manual (AFSC 2018).  A summary of the'}` `r if(annual.report){year}` `r if(annual.report){'ADP can be found in Section 1.3. The focus of this report is related to deployment, and the evaluation is at the trip level of the sampling hierarchy.'}`

CRAIG TEST AR
`r if(annual.report){'More information on the sampling design used by observers and the relationship between the sample design and catch estimation can be found in Cahalan and Faunce (2020) and the'}` `r if(annual.report){year}` `r if(annual.report){'Observer Sampling Manual (AFSC'}` `r if(annual.report){year-1}``r if(annual.report){').  A summary of the'}` `r if(annual.report){year}` `r if(annual.report){'ADP can be found in Section 1.3. The focus of this report is related to deployment, and the evaluation is at the trip level of the sampling hierarchy.'}`

ORIGINAL TM
`r if(tech.memo){'More information on the sampling design used by observers and the relationship between the sample design and catch estimation can be found in Cahalan and Faunce (2020) and the 2019 Observer Sampling Manual (AFSC 2018).  A summary of the'}` `r if(tech.memo){year}` `r if(tech.memo){'ADP is included below. The focus of this report is related to deployment, and the evaluation is at the trip level of the sampling hierarchy.'}`

`r if(tech.memo){'#The'}` `r if(tech.memo){year}` `r if(tech.memo){'Annual Deployment Plan'}`    
`r if(tech.memo){'The following briefly summarizes the final 2019 ADP (NMFS 2018). In general, all vessels that participate in cooperatives or act as catcher-processors or motherships are fully observed at the trip-level and constitute the full-coverage category of the fleet. In 2016, NMFS published new regulations to allow the owner of a trawl catcher vessel to annually request that NMFS place requesting vessels in the full coverage category for all directed fishing for groundfish using trawl gear in the Bering Sea and Aleutian Islands management area (BSAI) in the following calendar year. This regulated process has replaced an interim policy. For the 2019 calendar year, NMFS received and approved requests and has placed 18 catcher vessels in the full coverage category for all directed fishing for groundfish using trawl gear in the BSAI management area (NMFS 2018). The NMFS used only the trip-selection method (i.e., no vessel-selection) to assign observers and EM to vessels in the partial-coverage category for 2019. The partial-coverage category includes vessels greater than or equal to 40 feet (ft) length overall (LOA) and not in the full coverage category. There were seven sampling strata in the partial coverage category in 2019:'}`  

`r if(tech.memo){'1.  Hook-and-line vessels (*HAL* stratum).'}`    
`r if(tech.memo){'2.  Hook-and-line vessels with EM (*EM HAL* stratum).'}`     
`r if(tech.memo){'3.  Pot vessels not delivering to tenders (*POT - No Tender* stratum).'}`     
`r if(tech.memo){'4.	Pot vessels delivering to tenders (*POT - Tender* stratum).'}`
`r if(tech.memo){'5.  Pot vessels with EM (*EM POT* stratum).'}`
`r if(tech.memo){'6.	Trawl vessels not delivering to tenders (*TRW - No Tender* stratum).'}`     
`r if(tech.memo){'7.	Trawl vessels delivering to tenders (*TRW - Tender* stratum).'}`      
  
`r if(tech.memo){'Data collected through EM was first used in catch accounting in 2018, with the inclusion of *EM HAL* data. In 2019, data from the *EM POT* stratum were also used in catch accounting. Vessels had to volunteer to participate in the fixed gear EM Program by 1 November, 2018. The NMFS then selected vessels to be included in the EM Program following an evaluation of available funding (NMFS 2018, Appendix C). NMFS also sought vessels to participate in EM research and development activities. Vessels that volunteered for the fixed gear EM Program or EM research activities and were selected by the NMFS were not required to carry observers but were required to continue to log their fishing trips into the Observer Declare and Deploy System (ODDS). In this report, we attempt to evaluate the deployment of EM onto fixed gear vessels to the same degree as we evaluate the deployment of observers.'}` 
